AWSTemplateFormatVersion: "2010-09-09"
Description: CI/CD deployed Glue ETL job with environment support

Parameters:
  Environment:
    Type: String
    AllowedValues:
      - dev
      - test
      - prod
    Description: Deployment environment (dev/test/prod)

Resources:

  ################################
  # IAM ROLE FOR GLUE
  ################################
  GlueRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub glue-role-${Environment}
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: glue.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSGlueServiceRole

  ################################
  # GLUE JOB
  ################################
  GlueJob:
    Type: AWS::Glue::Job
    Properties:
      Name: !Sub netflix-etl-${Environment}
      Role: !GetAtt GlueRole.Arn
      Command:
        Name: glueetl
        ScriptLocation: glue/glue_job.py   # <-- FIXED (LOCAL PATH)
      GlueVersion: "4.0"
      WorkerType: G.1X
      NumberOfWorkers: 2
      DefaultArguments:
        "--ENV": !Ref Environment
        "--INPUT_PATH": !Sub s3://project-${Environment}-raw-cicd/netflix_titles.csv
        "--OUTPUT_PATH": !Sub s3://project-${Environment}-clean-cicd/netflix/
        "--enable-continuous-cloudwatch-log": "true"
        "--enable-metrics": "true"

  ################################
  # IAM ROLE FOR LAMBDA
  ################################
  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub lambda-role-${Environment}
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - arn:aws:iam::aws:policy/AWSGlueConsoleFullAccess

  ################################
  # TRIGGER LAMBDA (FIXED)
  ################################
  TriggerLambda:
    Type: AWS::Lambda::Function
    DependsOn:
      - GlueJob
      - LambdaRole
    Properties:
      FunctionName: !Sub glue-trigger-${Environment}
      Runtime: python3.10
      Handler: trigger.lambda_handler   # <-- FIXED
      Role: !GetAtt LambdaRole.Arn
      Timeout: 60
      CodeUri: lambda/                  # <-- CRITICAL FIX
      Environment:
        Variables:
          ENV: !Ref Environment
          GLUE_JOB_NAME: !Ref GlueJob

################################
# OUTPUTS
################################
Outputs:
  GlueJobName:
    Description: Glue Job Name
    Value: !Ref GlueJob

  LambdaFunctionName:
    Description: Trigger Lambda Function Name
    Value: !Ref TriggerLambda
