AWSTemplateFormatVersion: "2010-09-09"
Description: CI/CD Glue ETL with Lambda trigger from existing S3 bucket

Parameters:
  Environment:
    Type: String
    AllowedValues: [dev, test, prod]

  ArtifactBucket:
    Type: String

Resources:

# -------------------------------------------------
# GLUE ROLE
# -------------------------------------------------
  GlueExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub glue-execution-role-${Environment}
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: glue.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSGlueServiceRole
        - arn:aws:iam::aws:policy/AmazonS3FullAccess

# -------------------------------------------------
# GLUE JOB
# -------------------------------------------------
  GlueJob:
    Type: AWS::Glue::Job
    Properties:
      Name: !Sub glue-etl-job-${Environment}
      Role: !GetAtt GlueExecutionRole.Arn
      GlueVersion: "4.0"
      WorkerType: G.1X
      NumberOfWorkers: 2
      Command:
        Name: glueetl
        ScriptLocation: !Sub s3://project-${Environment}-scripts-cicd/glue/glue_job.py
      DefaultArguments:
        "--ENV": !Ref Environment

# -------------------------------------------------
# GLUE TRIGGER LAMBDA ROLE
# -------------------------------------------------
  GlueTriggerLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub glue-trigger-role-${Environment}
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: GlueInvoke
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: glue:StartJobRun
                Resource: "*"

# -------------------------------------------------
# GLUE TRIGGER LAMBDA
# -------------------------------------------------
  GlueTriggerLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub glue-trigger-${Environment}
      Runtime: python3.10
      Handler: trigger.lambda_handler
      Role: !GetAtt GlueTriggerLambdaRole.Arn
      Code:
        S3Bucket: !Ref ArtifactBucket
        S3Key: lambda/lambda.zip
      Environment:
        Variables:
          GLUE_JOB_NAME: !Ref GlueJob

# -------------------------------------------------
# PERMISSION FOR S3 TO INVOKE GLUE LAMBDA
# -------------------------------------------------
  AllowS3InvokeGlueLambda:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref GlueTriggerLambda
      Action: lambda:InvokeFunction
      Principal: s3.amazonaws.com
      SourceArn: !Sub arn:aws:s3:::project-${Environment}-raw-cicd

# -------------------------------------------------
# CUSTOM RESOURCE ROLE (MODIFIES EXISTING BUCKET)
# -------------------------------------------------
  S3NotificationCustomRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: S3NotificationPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - s3:PutBucketNotificationConfiguration
                Resource: !Sub arn:aws:s3:::project-${Environment}-raw-cicd

# -------------------------------------------------
# CUSTOM RESOURCE LAMBDA
# -------------------------------------------------
  S3NotificationLambda:
    Type: AWS::Lambda::Function
    Properties:
      Runtime: python3.10
      Handler: index.handler
      Role: !GetAtt S3NotificationCustomRole.Arn
      Timeout: 60
      Code:
        ZipFile: |
          import json, boto3, cfnresponse
          def handler(event, context):
              s3 = boto3.client("s3")
              bucket = event["ResourceProperties"]["Bucket"]
              lambda_arn = event["ResourceProperties"]["LambdaArn"]
              if event["RequestType"] in ["Create", "Update"]:
                  s3.put_bucket_notification_configuration(
                      Bucket=bucket,
                      NotificationConfiguration={
                          "LambdaFunctionConfigurations": [{
                              "LambdaFunctionArn": lambda_arn,
                              "Events": ["s3:ObjectCreated:*"]
                          }]
                      }
                  )
              cfnresponse.send(event, context, cfnresponse.SUCCESS, {})

# -------------------------------------------------
# CUSTOM RESOURCE
# -------------------------------------------------
  AttachNotificationToExistingBucket:
    Type: Custom::S3Notification
    DependsOn: AllowS3InvokeGlueLambda
    Properties:
      ServiceToken: !GetAtt S3NotificationLambda.Arn
      Bucket: !Sub project-${Environment}-raw-cicd
      LambdaArn: !GetAtt GlueTriggerLambda.Arn
