AWSTemplateFormatVersion: "2010-09-09"
Description: >
  CI/CD deployed Glue ETL job triggered by S3 uploads using a single Lambda,
  with environment-based isolation.

# -------------------------------------------------
# PARAMETERS
# -------------------------------------------------
Parameters:
  Environment:
    Type: String
    AllowedValues: [dev, test, prod]
    Description: Deployment environment

# -------------------------------------------------
# MAPPINGS
# -------------------------------------------------
Mappings:
  EnvToBucket:
    dev:
      DataBucket: project-dev-ci-cd-21166
    test:
      DataBucket: project-test-ci-cd-21166
    prod:
      DataBucket: project-prod-ci-cd-21166

# -------------------------------------------------
# RESOURCES
# -------------------------------------------------
Resources:

# -------------------------------------------------
# GLUE EXECUTION ROLE
# -------------------------------------------------
  GlueExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub glue-execution-role-${Environment}
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: glue.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSGlueServiceRole
      Policies:
        - PolicyName: GlueS3Access
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:DeleteObject
                  - s3:ListBucket
                Resource:
                  - !Sub
                    - arn:aws:s3:::${EnvBucket}
                    - EnvBucket: !FindInMap [EnvToBucket, !Ref Environment, DataBucket]
                  - !Sub
                    - arn:aws:s3:::${EnvBucket}/*
                    - EnvBucket: !FindInMap [EnvToBucket, !Ref Environment, DataBucket]

# -------------------------------------------------
# GLUE JOB
# -------------------------------------------------
  GlueJob:
    Type: AWS::Glue::Job
    Properties:
      Name: !Sub glue-log-aggregation-${Environment}
      Role: !GetAtt GlueExecutionRole.Arn
      GlueVersion: "4.0"
      WorkerType: G.1X
      NumberOfWorkers: 2
      Command:
        Name: glueetl
        ScriptLocation: !Sub
          - s3://${EnvBucket}/scripts/glue/log_aggregation_job.py
          - EnvBucket: !FindInMap [EnvToBucket, !Ref Environment, DataBucket]
        PythonVersion: "3"
      DefaultArguments:
        --ENV: !Ref Environment
        --INPUT_PATH: !Sub
          - s3://${EnvBucket}/raw/
          - EnvBucket: !FindInMap [EnvToBucket, !Ref Environment, DataBucket]
        --OUTPUT_PATH: !Sub
          - s3://${EnvBucket}/clean/
          - EnvBucket: !FindInMap [EnvToBucket, !Ref Environment, DataBucket]
        --job-bookmark-option: job-bookmark-enable
        --enable-continuous-cloudwatch-log: "true"
        --enable-metrics: ""
      ExecutionProperty:
        MaxConcurrentRuns: 1

# -------------------------------------------------
# LAMBDA ROLE – GLUE TRIGGER
# -------------------------------------------------
  GlueTriggerLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub glue-trigger-lambda-role-${Environment}
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: LambdaGluePolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - glue:StartJobRun
                Resource: !Sub arn:aws:glue:${AWS::Region}:${AWS::AccountId}:job/glue-log-aggregation-${Environment}

# -------------------------------------------------
# SINGLE LAMBDA FUNCTION – S3 → GLUE
# -------------------------------------------------
  GlueTriggerLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub glue-trigger-${Environment}
      Runtime: python3.10
      Handler: lambda_function.lambda_handler
      Role: !GetAtt GlueTriggerLambdaRole.Arn
      Timeout: 60
      Code:
        S3Bucket: !FindInMap [EnvToBucket, !Ref Environment, DataBucket]
        S3Key: scripts/lambda/glue_trigger_lambda.zip
      Environment:
        Variables:
          ENV: !Ref Environment
          GLUE_JOB_NAME: !Ref GlueJob
          DATA_BUCKET: !FindInMap [EnvToBucket, !Ref Environment, DataBucket]

# -------------------------------------------------
# PERMISSION FOR S3 TO INVOKE LAMBDA
# -------------------------------------------------
  AllowS3InvokeGlueLambda:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref GlueTriggerLambda
      Action: lambda:InvokeFunction
      Principal: s3.amazonaws.com
      SourceArn: !Sub
        - arn:aws:s3:::${EnvBucket}
        - EnvBucket: !FindInMap [EnvToBucket, !Ref Environment, DataBucket]

# -------------------------------------------------
# S3 BUCKET NOTIFICATION → LAMBDA
# -------------------------------------------------
  DataBucketNotification:
    Type: AWS::S3::BucketNotification
    DependsOn: AllowS3InvokeGlueLambda
    Properties:
      Bucket: !FindInMap [EnvToBucket, !Ref Environment, DataBucket]
      NotificationConfiguration:
        LambdaConfigurations:
          - Event: s3:ObjectCreated:*
            Filter:
              S3Key:
                Rules:
                  - Name: prefix
                    Value: raw/
            Function: !GetAtt GlueTriggerLambda.Arn

# -------------------------------------------------
# OUTPUTS
# -------------------------------------------------
Outputs:
  GlueJobName:
    Value: !Ref GlueJob

  LambdaFunctionName:
    Value: !Ref GlueTriggerLambda

  DataBucket:
    Value: !FindInMap [EnvToBucket, !Ref Environment, DataBucket]
