AWSTemplateFormatVersion: "2010-09-09"
Description: CI/CD deployed Glue ETL job with environment support

Parameters:
  Environment:
    Type: String
    AllowedValues:
      - dev
      - test
      - prod
    Description: Deployment environment (dev/test/prod)

Resources:

  GlueExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub glue-execution-role-${Environment}
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: glue.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSGlueServiceRole

  GlueJob:
    Type: AWS::Glue::Job
    Properties:
      Name: !Sub glue-etl-job-${Environment}
      Role: !GetAtt GlueExecutionRole.Arn
      Command:
        Name: glueetl
        ScriptLocation: glue/glue_job.py
      GlueVersion: "4.0"
      ExecutionProperty:
        MaxConcurrentRuns: 1
      MaxRetries: 0
      Timeout: 10
      NumberOfWorkers: 2
      WorkerType: G.1X
      DefaultArguments:
        "--job-language": "python"
        "--environment": !Ref Environment
